import httpx
import time
import random

PROMPTS = [
    # simple - factual
    "What is the capital of France?",
    "What is the currency of Japan?",
    "Who painted the Mona Lisa?",
    "What is the largest ocean on Earth?",
    "What is the chemical symbol for gold?",
    "Who wrote Romeo and Juliet?",
    "What is the tallest mountain in the world?",
    "What is the full form of HTTP?",
    "Who is the founder of Facebook?",
    "What is the capital of South Korea?",
    "What is the square root of 144?",
    "What programming language is Django built on?",
    "What is the full form of CPU?",
    "What is the capital of Egypt?",
    "Who invented the airplane?",
    "What is the largest country by area?",
    "Who is the CEO of Tesla?",
    "What is 15 multiplied by 7?",
    "Define machine learning",
    "What is the capital of Japan?",
    "How many planets are in the solar system?",
    "What is the boiling point of water?",
    "Who invented the telephone?",
    "What is the speed of light?",
    "Define neural network",
    "What is the capital of Germany?",
    "Who founded Microsoft?",
    "What is 256 divided by 16?",
    "What is the capital of Australia?",
    "Who wrote Harry Potter?",
    "What is the atomic number of carbon?",
    "What is RAM in computers?",
    "Who invented the internet?",
    "What is the capital of Brazil?",
    "What is Python programming language?",
    "Who is the founder of Amazon?",
    "What is the largest planet in the solar system?",
    "What is SQL?",
    "What is the capital of Canada?",
    "Who invented the light bulb?",
    "What is an API?",
    "What is the capital of India?",
    "What is machine learning?",
    "Who founded Google?",
    "What is the speed of sound?",
    "What is the capital of China?",
    "Define deep learning",
    "What is Docker?",
    "Who invented electricity?",
    "What is the capital of Russia?",
    "What is Kafka?",
    "Who founded Apple?",
    "What is Redis?",
    "What is the capital of Italy?",
    "What is PostgreSQL?",
    "What is the capital of Mexico?",
    "Who invented the steam engine?",
    "What is the chemical formula for water?",
    "What is the largest continent?",
    "Who wrote the theory of relativity?",
    "What is the capital of Argentina?",
    "What is the full form of AI?",
    "Who is the founder of Twitter?",
    "What is the capital of Nigeria?",
    "What is the boiling point of water in Fahrenheit?",
    "What is the full form of GPU?",
    "What is the capital of Pakistan?",
    "Who invented the printing press?",
    "What is the largest mammal on Earth?",
    "What is the capital of Turkey?",
    "What is the full form of URL?",
    "Who is the founder of Tesla?",
    "What is the capital of Saudi Arabia?",
    "What is the square root of 256?",
    "What is the full form of RAM?",
    "What is the capital of Indonesia?",
    "Who invented the telescope?",
    "What is the largest desert on Earth?",
    "What is the capital of Thailand?",
    "What is the full form of DNS?",
    "Who is the founder of Netflix?",
    "What is the capital of Colombia?",
    "What is 100 divided by 4?",
    "What is the full form of IP?",
    "What is the capital of Ukraine?",
    "Who invented the microscope?",
    "What is the deepest ocean on Earth?",
    "What is the capital of Malaysia?",
    "What is the full form of CSS?",
    "Who is the founder of Uber?",
    "What is the capital of Kenya?",
    "What is 17 multiplied by 8?",
    "What is the full form of HTML?",
    "What is the capital of Vietnam?",
    "Who invented the radio?",
    "What is the smallest planet in the solar system?",
    "What is the capital of Peru?",
    "What is the full form of JSON?",
    "Who is the founder of LinkedIn?",
    "What is the capital of Bangladesh?",
    "What is 512 divided by 8?",
    "What is the full form of XML?",
    "What is the capital of Ghana?",
    "Who invented calculus?",
    "What is the capital of Morocco?",
    "What is the full form of JWT?",
    "Who is the founder of Airbnb?",
    "What is the capital of Ethiopia?",
    "What is 23 multiplied by 4?",
    "What is the full form of REST?",
    "What is the capital of Myanmar?",
    "Who invented the compass?",
    "What is the hottest planet in the solar system?",
    "What is the capital of Ecuador?",
    "What is the full form of gRPC?",
    "Who is the founder of Spotify?",
    "What is the capital of Angola?",
    "What is 1024 divided by 32?",
    "What is the full form of SMTP?",
    "What is the capital of Uzbekistan?",
    "Who invented the battery?",
    "What is the closest star to Earth?",
    "What is the capital of Kazakhstan?",
    "What is the full form of TCP?",
    "Who is the founder of Slack?",
    "What is the capital of Zimbabwe?",
    "What is 45 multiplied by 6?",
    "What is the full form of UDP?",
    "What is the capital of Nepal?",
    "Who invented the calculator?",
    "What is the largest organ in the human body?",
    "What is the capital of Sri Lanka?",
    "What is the full form of SSH?",
    "Who is the founder of Discord?",
    "What is the capital of Bolivia?",
    "What is 999 divided by 3?",
    "What is the full form of VPN?",
    "What is the capital of Cuba?",
    "Who invented the X-ray?",
    "What is the fastest land animal?",
    "What is the capital of Guatemala?",
    "What is the full form of CDN?",
    "Who is the founder of Zoom?",
    "What is the capital of Tanzania?",
    "What is 36 multiplied by 9?",
    "What is the full form of OAuth?",
    "What is the capital of Cameroon?",
    "Who invented penicillin?",
    "What is the longest river in the world?",
    "What is the capital of Jordan?",
    "What is the full form of CORS?",
    "Who is the founder of Stripe?",
    "What is the capital of Tunisia?",
    # complex - explanations
    "Explain how transformer models handle long context windows",
    "Explain how vector embeddings are used in semantic search",
    "Describe the differences between bagging and boosting in ensemble learning",
    "How does the BERT pre-training process work?",
    "Explain the concept of positional encoding in transformers",
    "Describe how knowledge graphs differ from relational databases",
    "How does contrastive learning work in self-supervised learning?",
    "Explain the differences between synchronous and asynchronous programming",
    "Describe how a bloom filter works and its use cases",
    "How does the Adam optimizer differ from SGD?",
    "Explain the concept of dead letter queues in message systems",
    "Describe how LLM tokenization works with byte pair encoding",
    "How does multi-task learning improve model generalization?",
    "Explain the tradeoffs between batch size and learning rate",
    "Describe how semantic versioning works in software development",
    "How does the attention mask work in transformer models?",
    "Explain the concept of model collapse in generative AI",
    "Describe how online learning differs from batch learning",
    "How does temperature sampling affect LLM outputs?",
    "Explain the working of cross-entropy loss in classification",
    "Describe how sparse attention reduces transformer complexity",
    "How does retrieval augmented generation improve LLM accuracy?",
    "Explain the differences between precision, recall and F1 score",
    "Describe how A/B testing works in machine learning systems",
    "How does weight initialization affect neural network training?",
    "Explain the concept of catastrophic forgetting in neural networks",
    "Describe how mixture of experts routing works in LLMs",
    "How does the KV cache improve LLM inference speed?",
    "Explain the differences between encoder and decoder transformers",
    "Describe how data augmentation improves model robustness",
    "How does early stopping prevent overfitting in deep learning?",
    "Describe the differences between generative and discriminative models",
    "How does reinforcement learning differ from supervised learning?",
    "Explain the concept of attention sink in large language models",
    "Describe how neural networks learn hierarchical representations",
    "How does the softmax function work in classification tasks?",
    "Explain the concept of residual connections in deep learning",
    "Describe how knowledge distillation works between teacher and student models",
    "How does beam search work in sequence generation?",
    "Explain the differences between word2vec and GloVe embeddings",
    "Describe how multi-modal models process text and images together",
    "How does the transformer encoder differ from the decoder?",
    "Explain the concept of fine-tuning vs full training in LLMs",
    "Describe how sparse transformers reduce computational complexity",
    "How does nucleus sampling work in language model generation?",
    "Explain the concept of perplexity in language model evaluation",
    "Describe how chain of thought prompting improves reasoning",
    "How does the mixture of experts architecture scale LLMs?",
    "Explain the differences between autoregressive and masked language models",
    "Describe how retrieval augmented generation reduces hallucination",
    "How does constitutional AI work in model alignment?",
    "Explain the concept of model parallelism in distributed training",
    "Describe how the RLHF pipeline works step by step",
    "How does in-context learning work in large language models?",
    "Explain the differences between soft and hard prompting",
    "Describe how neural scaling laws affect model performance",
    "How does speculative decoding speed up LLM inference?",
    "Explain the concept of emergent abilities in large language models",
    "Describe how instruction tuning improves LLM helpfulness",
    "How does the attention mechanism handle variable length sequences?",
    "Explain the differences between BERT and RoBERTa",
    "Describe how data parallelism works in distributed deep learning",
    "How does gradient checkpointing reduce memory usage in training?",
    "Explain the concept of tokenization and its effect on LLM performance",
    "Describe how low rank adaptation (LoRA) works for fine-tuning",
    "How does the cosine learning rate schedule work?",
    "Explain the differences between causal and non-causal attention",
    "Describe how semantic similarity is measured in NLP",
    "How does the transformer handle positional information differently from RNNs?",
    "Explain the concept of model calibration in machine learning",
    "Describe how active learning reduces labeling costs",
    "How does contrastive loss work in representation learning?",
    "Explain the differences between token classification and sequence classification",
    "Describe how cross-lingual transfer learning works",
    "How does the attention pattern differ between encoder and decoder layers?",
    "Explain the concept of prompt injection attacks in LLMs",
    "Describe how model merging works in machine learning",
    "How does the KV cache work during autoregressive generation?",
    "Explain the differences between zero-shot and few-shot learning",
    "Describe how neural machine translation has evolved with transformers",
    "How does data poisoning affect machine learning models?",
    "Explain the concept of catastrophic forgetting and how to prevent it",
    "Describe how ensemble methods improve prediction accuracy",
    "How does the learning rate warmup strategy work in transformer training?",
    "Explain the differences between batch normalization and layer normalization",
    "Describe how multi-task learning shares representations across tasks",
    "How does the attention head pruning work in model compression?",
    "Explain the concept of dataset bias and its effect on model fairness",
    "Describe how neural architecture search automates model design",
    "How does the sliding window attention work for long sequences?",
    "Explain the differences between open source and closed source LLMs",
    "Describe how model quantization affects inference speed and accuracy",
    "How does the teacher forcing technique work in sequence to sequence models?",
    "Explain the concept of reward hacking in reinforcement learning",
    "Describe how self-supervised learning creates training signals",
    "How does the mixture of experts gating mechanism work?",
    "Explain the differences between greedy decoding and sampling",
    "Describe how neural network pruning reduces model size",
    "How does the attention dropout work as regularization?",
    "Explain the concept of model distillation for edge deployment",
    "Describe how semantic search differs from traditional keyword search",
    "How does the prefix tuning approach work for LLM adaptation?",
    "Explain the differences between online and offline reinforcement learning",
    "Describe how data augmentation strategies work for NLP tasks",
    "How does the adaptive computation time work in transformers?",
    "Explain the concept of hallucination mitigation strategies in LLMs",
    "Describe how neural text generation is evaluated beyond perplexity",
    "How does the rotary position embedding work in modern LLMs?",
    "Explain the differences between parameter efficient fine-tuning methods",
    "Describe how multi-head attention captures different linguistic features",
    "How does the flash attention algorithm improve transformer efficiency?",
    "Explain the concept of emergent few-shot learning in large models",
    "Describe how adversarial training improves model robustness",
    "How does the cross-attention mechanism work in encoder-decoder models?",
    "Explain the differences between token and character level language models",
    "Describe how model watermarking works for LLM output detection",
    "How does the gradient accumulation technique work in training?",
    "Explain the concept of model alignment and its importance in AI safety",
    "Describe how retrieval augmented generation handles knowledge updates",
    "How does the parallel decoding approach speed up LLM inference?",
    "Explain the differences between supervised and self-supervised pre-training",
    "Describe how neural networks approximate arbitrary functions",
    "How does the attention bias work in causal language modeling?",
    "Explain the concept of model collapse in continual learning",
    "Describe how semantic parsing converts natural language to structured queries",
    "How does the grouped query attention reduce memory in LLMs?",
    "Explain the differences between extractive and abstractive summarization",
    "Describe how the CLIP model aligns text and image representations",
    "How does the chain of thought prompting improve multi-step reasoning?",
    "Explain the architectural differences between transformer and RNN based language models briefly",
    "Describe how attention mechanisms work in deep learning",
    "Compare supervised and unsupervised learning with examples",
    "Explain how Kafka achieves fault tolerance in distributed systems",
    "Analyze the tradeoffs between SQL and NoSQL databases",
    "Explain how Redis handles cache eviction policies",
    "Describe the CAP theorem and its implications",
    "How does backpropagation work in neural networks?",
    "Explain the difference between L1 and L2 regularization",
    "Discuss the ethical implications of large language models",
    "Explain how BERT differs from GPT in architecture and use cases",
    "Describe the working of a convolutional neural network in detail",
    "How does the transformer positional encoding work?",
    "Explain the concept of transfer learning in deep learning",
    "Compare microservices and monolithic architecture with tradeoffs",
    "How does consistent hashing work in distributed systems?",
    "Explain the differences between TCP and UDP protocols",
    "Describe how garbage collection works in Java",
    "How does a load balancer work in a distributed system?",
    "Explain the SOLID principles in software engineering",
    "Describe how vector databases work and their use cases",
    "How does RAG (Retrieval Augmented Generation) work?",
    "Explain the concept of embeddings in NLP",
    "Describe the differences between LSTM and GRU architectures",
    "How does the Adam optimizer work in deep learning?",
    "Explain how distributed transactions work with two-phase commit",
    "Describe the working of a recommendation system",
    "How does Docker containerization differ from virtual machines?",
    "Explain the concept of attention in transformers with an example",
    "Describe how Kubernetes manages container orchestration",
    "How does gradient descent optimization work?",
    "Explain the differences between batch and stream processing",
    "Describe how a content delivery network (CDN) works",
    "How does OAuth 2.0 authentication work?",
    "Explain the concept of zero-shot learning in AI",
    "Describe the working of a graph neural network",
    "How does database indexing improve query performance?",
    "Explain the differences between supervised fine-tuning and RLHF",
    "Describe how MapReduce works in big data processing",
    "How does the PageRank algorithm work?",
    "Explain the concept of model quantization in deep learning",
    "Describe how event sourcing works in distributed systems",
    "How does a variational autoencoder work?",
    "Explain the differences between precision and recall in ML",
    "Describe how knowledge distillation works in machine learning",
    "How does HTTPS encryption work?",
    "Explain the working of a generative adversarial network",
    "Describe how prompt engineering affects LLM outputs",
    "How does federated learning work?",
    "Explain the concept of hallucination in large language models",
    "Describe the differences between fine-tuning and prompt engineering",
    "How does a message queue differ from a database?",
    "Explain the working of the RAFT consensus algorithm",
    "Describe how neural architecture search works",
    "How does semantic search differ from keyword search?",
    "Explain the concept of chain of thought prompting",
    "Describe how LLM inference optimization works with quantization",
    "How does the mixture of experts architecture work in LLMs?",
    "Explain the concept of context window in language models",
    "Describe how reinforcement learning from human feedback works",
    "How does multi-head attention improve transformer performance?",
]

def send_prompt(prompt: str):
    try:
        response = httpx.post(
            "http://127.0.0.1:8000/api/v1/chat",
            json={"prompt": prompt},
            timeout=30.0
        )
        data = response.json()
        print(f"✓ [{data['complexity']}] [{data['provider']}] {prompt[:40]}... ({data['latency_ms']}ms)")
    except httpx.TimeoutException:
        print(f"✗ Timeout, skipping: {prompt[:40]}")
    except Exception as e:
        print(f"✗ Error: {e}")

if __name__ == "__main__":
    total = 0
    maxCap = 10000
    print(f"Starting simulator... Target: {maxCap} requests")
    while total < maxCap:
        prompt = random.choice(PROMPTS)
        try:
            send_prompt(prompt)
            total += 1
            print(f"Progress: {total}/{maxCap}")
        except Exception as e:
            print(f"Error: {e}")
    print(f"Done! {maxCap} traces generated.")